### PR TITLE
Improve tests

### PR DESCRIPTION
**Pull request by Nibbler999**
The test image was missing the EOI marker bytes, I've added these.
Added tests for the various ways the response may be chunked.
Added test for the bytesWritten property.

### CODE REVIEW

**Comment by mmaelzer** [comment]
Thanks for the additional tests! I'll go ahead and merge this and adjust some formatting. For js code, I prefer camelCase over snake_case.

Also, you've again shown me that I'm missing the EOI marker bytes in my implementation as the test image was captured from running a test script against http://mjpeg.sanford.io/count.mjpeg.

What bugs are preventing you from using it in your application? I'd be happy to fix them.

**Comment by mmaelzer** [comment]
Perhaps these tests are showing me where you're seeing bugs in your application eh?

**Comment by mmaelzer** [comment]
Those tests definitely revealed some bugs. All tests pass in eef6d246db6f7bc7ce8851fae9848765c90b0730

**Comment by mmaelzer** [comment]
Bah still bugs. Looking into them.

**Comment by mmaelzer** [comment]
Alright, all should be well now. Let me know if you find any other issues.

**Comment by Nibbler999** [comment]
All working now, thanks. There are some unwanted files in the npm package though.

**Comment by mmaelzer** [comment]
Hu, TIL that npm uses all files in a folder, not just files tracked by git. Which kinda makes sense. Updated the npm package.

**Pull request merged**
